name: Docker

run-name: Build and push Docker image

on:
  push:
    tags:
      - "v*.*.*-bot"

env:
  GITEA_REGISTRY: gitea.antoine-langlois.net
  GH_REGISTRY: ghcr.io
  GH_REPOSITORY: wyll-io/tech-bot
  GITEA_REPOSITORY: datahearth/tech-bot

jobs:
  build-push-services:
    name: Build and push service images

    needs: build-push-builder
    runs-on: debian-docker

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log into registry Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log into registry Gitea
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GITEA_REGISTRY }}
          username: ${{ gitea.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Log into registry GitHub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ gitea.repository_owner }}
          password: ${{ secrets.GH_REGISTRY_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.GITEA_REPOSITORY }}
            ${{ env.GITEA_REGISTRY }}/${{ env.GITEA_REPOSITORY }}
            ${{ env.GH_REGISTRY }}/${{ env.GH_REPOSITORY }}
          tags: |
            type=semver,pattern=bot-latest
            type=semver,pattern=bot-{{version}}
            type=semver,pattern=bot-{{major}}.{{minor}}
          flavor: |
            latest=false

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          target: bot
          cache-to: type=inline
          cache-from: |
            type=registry,ref=${{ env.GITEA_REPOSITORY }}:bot-latest
            type=registry,ref=${{ env.GITEA_REGISTRY }}/${{ env.GITEA_REPOSITORY }}:bot-latest
            type=registry,ref=${{ env.GH_REGISTRY }}/${{ env.GH_REPOSITORY }}:bot-latest
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
