name: Rust

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: debian-rust
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tests
        run: cargo test --verbose
